baseurl = "https://example.com/"
languageCode = "en_US"
title = "Hugo Tikva Theme"

theme = "hugo-tikva"

# Language setting of the site, for language configuration see
#  https://gohugo.io/content-management/multilingual/
# There are only a few strings which need to be translated, feel free to add more
# languages.
DefaultContentLanguage = "en" # current values: "en" or "de"

# To enable a demo of pagination, this value is set to 2 instead of the default. See https://gohugo.io/getting-started/configuration/
# for all site variables. The paginate default is 10
paginate = 2

# Google Analytics setting, see Hugo internal templates
#googleAnalytics = "UA-123-45"


# For all color settings, please use the format "#rrggbb". 

# Generic parameters
[params]
    appendSiteTitle = true # Append site title to title tag on every page. Default false
    #favicon = 'img/favicon.ico' # Add favicon, default empty
    subtitle = "Example of Subtitle"

    dateFormat = "02.01.2006" # Format dates with Go's time formatting
    showDate = true # true|false: Show date on summaries. This is a global setting. If the date should be shown, you have to add a "date" parameter to the content files, otherwise the default value will be used, which is something you don't want.
    showNumberOfWords = false # true|false: Show number of word on article header of single content page
    hideMeta = false # Hide meta information on single pages


# Navigation bar settings

[params.navbar]
    style = "header" # Navigation bar style, values "fixed-top" or "header", default is fixed-top 
    
    colorScheme = "navbar-dark" # navbar-light, navbar-dark
    
    bgScheme = "bg-primary" # see Bootstrap docs, bg.* utilities https://getbootstrap.com/docs/4.1/utilities/colors/
    
    backgroundColor = ''  # custom background color parameters, e.g. #e3f2fd !important, If color is set, it will be used for background. Set empty for above selection.
    
    adjustHeader = 20 # Adjust header by adding a distance between navigation and content. Some of the styles need more space, so you can use this option to adjust. Use an integer value of pixels.
    
    textAlignment = '' # don't set or leave empty for default (left), or justify-content-end, justify-content-center

    #brandImage = 'img/rg_mod_20.png' # The "brand image" will be set in "fixed-top" style as icon beside the site title. 


# Meta header parameter settings

# You can add as many rows as you want, every row defines a meta tag with its key and value. 
# The content will be included in the head of the site as: <meta name="_key_" content="_value_">.

[params.meta]
    description = "This is only an example value for the meta description"
    keywords = "example, site, theme, tikva"
    author = "John Doe"
    "DC.Copyright" = "Karl Mustermann"
    

# Theme configuration

[params.theme]

    bootstrapTheme = 'solar' # Use empty value for default Bootstrap color scheme or one of the following values:
    # bolt, bstrap, btcn, calabaza, cerulean, cosmo, cyborg, darkly, flatly, hoff, journal,
    # kdo_flatly, kdo2, kunsch, lumen, lux, malibu, materia, minim, minty, pulse, sandstone, 
    # signa, simplex, sketchy, slate_accessibility_ready, slate, solar, sonic, spacelab, united, yeti

    backgroundColor = '' # If color is set, it will be used for background. Set empty for default.
    backgroundImage = '' # Set background image, use file name with path in static folder, e.g. 'img/background.jpg'
    backgroundImageRepeat = '' # Set background image repeat option, see https://developer.mozilla.org/de/docs/Web/CSS/background-repeat


# Header configuration

[params.theme.header]
    # The following options are mostly used when the navbar is in "header" mode, i.e. not fixed-top
    fontColor = '' # header font color, leave empty for default
    linkColor = '' # header link color, leave empty for default
    backgroundColor = '' # header background color, leave empty for default

    image = 'img/header_bg_example.jpg' # Use header image. This option is only valid if the theme is configured to the "header" style. 
    
    width = 2512 # Width of header image. Please set this value to the correct size, because it will be used for size calculation.
    height = 673 # Height of header image. Please set this value to the correct size, because it will be used for size calculation.
    altText = 'alt text for header image' # Set alt text for header image, default empty
    displayHeaderText = true # display the title and subtitle - yes or no?
    titleOnImage = true # true|false, default false. Display title and subtitle as overlay in the foreground of the image. It is only possible to set the title as image overlay if an image is available. If no image is configured, the theme will do a fallback to non-overlay, i.e. title and subtitle will be displayed above the main navigation. 
    fontColorTitle = '#073642' # For all colors, please use #rrggbb format with # and 6 characters
    fontColorSubtitle = '#333333'
    overlayAlignment = 'lt' # lt = left/top, mt = middle/top, rt = right/top, lb = left/bottom, mb = middle/bottom, rb = right/bottom
    overlayDistanceVertical = '20' # Dependent on the overlayAlignment option, this option is used to modify the vertical distance between the margin and the title/subtitle. This allows to place the title and subtitle on nearly any place related to the header image. 
    overlayDistanceHorizontal = '20' # The same as above, but for horizontal distance. 
    overlayDistanceBetween = '0' # Distance between title and subtitle 
    overlayBackgroundColor = '#000000'
    overlayTransparency = '0' # default 70%, allowed values from 0 - 100 (without % sign!). This option enables a transparent background of title and subtitle. This is useful if the "titleOnImage" option is true, so the title is placed as overlay above the image. If this option is set to 0 or an empty value, the transparency color setting will be disabled. 

# Footer configuration

# To create a footer, create a directory "sections/footer" into your project’s content directory.
# Then add some content files (.md or .html) to the footer folder AND create an index.md file with the Front Matter setting
# headless: true
# Without the "headless" setting the sidebar will not be displayed! 
# See https://gohugo.io/content-management/page-bundles/#headless-bundle 
# You can modify the style with a partial "footer_column.html", see example in "layouts/partials/".

[params.theme.footer]
    enabled = true # Show the footer part
    #numberColumns = 3 # Set number of columns available in footer of a page. Use the "footer" folder in the page structure to add content. If nothing is set, the default number is 3. Currently.i.e. since v0.2 not used, the number of columns is identical to the number of files in footer directory.
    fontColor = '#f9fcf9' # set #rgb code, leave empty for default
    linkColor = '' # Set color of links as #rrggbb code, leave empty for default
    backgroundColor = '#29281f' # Set color of background as #rrggbb code, leave empty for default

# Subfooter configuration

# To create a subfooter, create a directory "sections/subfooter" into your project’s content directory.
# Then add some content files (.md or .html) to the subfooter folder AND create an index.md file with the Front Matter setting
# headless: true
# Without the "headless" setting the sidebar will not be displayed! 
# See https://gohugo.io/content-management/page-bundles/#headless-bundle 
# You can modify the style with a partial "subfooter_item.html", see example in "layouts/partials/".

[params.theme.subfooter]
    enabled = true # Show the content below the footer
    fontColor = '' # Text color in subfooter. Leave empty to use the theme default. 
    linkColor = '' # Link color in subfooter. Leave empty to use the theme default. 
    backgroundColor = '' # Background color of subfooter. Leave empty to use the theme default. 

# Font configuration

# In this section it is possible to modify the font settings of title, subtitle, navigation bar, body (i.e. the default text used in the content areas) and headlines h1 - h6. You can use Google Fonts as well as any font string the browser supports. 

[params.fonts]
   
    headerTitle = 'Exo' # set font, use string, e.g. "Lucida, Verdana, sans-serif". You can use any font value. Please activate Google Font option if you want to include Google Fonts, see their names on https://fonts.google.com/
    headerTitleGoogleFont = true # If the font in the above variable is a Google font, set this option to true. 
    headerTitleVariant = '800' # font variant, if available, e.g. "regular", "bold" etc. Not every font is available in multiple variants.
    headerTitleSize = '50px' # set font size, empty for default settings. Valid values are '20px', '1.2em' and so on
    
    headerSubtitle = 'Exo' # Font settings for subtitle
    headerSubtitleGoogleFont = true # If the font in the above variable is a Google font, set this option to true. 
    headerSubtitleVariant = '600' # See above
    headerSubtitleSize = '30px' # See above

    #navbar = 'Lucida, Verdana' # font settings for navigation bar
    navbarGoogleFont = false # If the font in the above variable is a Google font, set this option to true.  
    navbarVariant = '' # See above
    navbarSize = '20px' # See above

    body = '' # font settings for body content
    bodyGoogleFont = false # If the font in the above variable is a Google font, set this option to true. 
    bodyVariant = '' # See above
    bodySize = '' # See above

    headline = 'Open Sans' # font settings for body content
    headlineGoogleFont = true # If the font in the above variable is a Google font, set this option to true. 
    headlineVariant = '' # See above
    headlineBaseSize = '' # Set base font of headlines. The real size of H1 - H6 will be calculated based on this size with the same resize factors as in the CSS framework. Choose a size of 0 (zero) to use the default font size of the theme. Please use only integer values without "px", "em" or something else. 


# Web analytics configuration

# For Google Analytics, set the googleAnalytics config option to use internal Google Analytics template as described on
# https://gohugo.io/templates/internal/ 
# The config option has to be in the first level above the [params] section!

# This theme includes the standard embed codes for Matomo and Yandex Metrica. If you have configured some special options, you can simply overwrite the analytics partials. Just place the snippet code in the file "layouts/partials/analytics/matomo.html" or "layouts/partials/analytics/yandexmetrica.html" in your site folder. Or copy the theme partials from their path and change their options. If you have added custom snippet files, Hugo's lookup order will use your partial file at first. 

[params.analytics.matomo]
    enabled = false # Enable Matomo web analytics
    url = 'https://analytics.example.com' # URL of Matomo application
    siteId = 0 # Matomo site id. Provided by Matomo when a site is added.

[params.analytics.yandexmetrica]
    enabled = false # Enable Yandex Metrica
    tagNumber = '012345678' # Tag ID / number as seen on Yandex Metrica settings page
    
# Sidebar section

# To create a sidebar, create a directory "sections/sidebar" into your project’s content directory.
# Then add some content files (.md or .html) to the sidebar folder AND create an index.md file with the Front Matter setting
# headless: true
# Without the "headless" setting the sidebar will not be displayed! 
# See https://gohugo.io/content-management/page-bundles/#headless-bundle 
# You can modify the style with a partial "sidebar_item.html", see example in "layouts/partials/".

[params.sidebar]
    enabled = true # default false; set to true to enable sidebar
    style = 'right' # options: 'left', 'right'. Left means sidebar on the left side, right displays the sidebar on the right side


# Menu section

# This is an example of the main menu. You can also use the in-file setting in the header of the content files. 

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10


  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 20


  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

    
  
  [[menu.main]]
    name = "Feedback"
    url = "/feedback/"
    weight = 40

